# ============================================================
# SONARQUBE - Configuración del proyecto Angular
# Semana 7 - DSY2205 Desarrollo Full Stack III
# ============================================================

# Identificador único del proyecto en SonarQube
sonar.projectKey=biblioteca-frontend

# Nombre que aparece en el dashboard de SonarQube
sonar.projectName=Biblioteca Frontend - Angular

# Versión del proyecto
sonar.projectVersion=1.0

# Directorio raíz del código fuente
sonar.sources=src

# Archivos de test (excluidos del análisis de código fuente)
sonar.tests=src

# Inclusión de archivos de test
sonar.test.inclusions=**/*.spec.ts

# Exclusiones del análisis
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/coverage/**,**/dist/**

# Ruta al reporte de cobertura generado por Karma
sonar.javascript.lcov.reportPaths=coverage/biblioteca-frontend/lcov.info

# Codificación del proyecto
sonar.sourceEncoding=UTF-8

# URL del servidor SonarQube local (Docker)
sonar.host.url=http://localhost:9000

# Token de autenticación (reemplazar con el token generado en SonarQube)
# sonar.token=squ_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
