# ============================================================
# docker-compose.yml - Biblioteca FullStack
# DSY2205 - Semana 6 - Actividad Formativa 4
#
# Servicios:
#   1. biblioteca-backend   → Spring Boot      (puerto 8082)
#   2. biblioteca-frontend  → Angular + Nginx  (puerto 4200)
#
# INSTRUCCIONES DE USO:
#   1. docker-compose up --build
#   2. FrontEnd : http://localhost:4200
#   3. BackEnd  : http://localhost:8082/api/libros
#
# PARA SUBIR A DOCKER HUB (reemplazar TU_USUARIO):
#   docker-compose build
#   docker tag biblioteca-backend TU_USUARIO/biblioteca-backend:latest
#   docker tag biblioteca-frontend TU_USUARIO/biblioteca-frontend:latest
#   docker push TU_USUARIO/biblioteca-backend:latest
#   docker push TU_USUARIO/biblioteca-frontend:latest
# ============================================================

services:

  # ── BackEnd Spring Boot + Oracle Cloud ───────────────────────
  biblioteca-backend:
    build:
      context: ./biblioteca-s4
      dockerfile: Dockerfile
    container_name: biblioteca-backend
    image: biblioteca-backend:latest
    ports:
      - "8082:8082"
    environment:
      - DB_URL=jdbc:oracle:thin:@(description=(retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.sa-santiago-1.oraclecloud.com))(connect_data=(service_name=g1c6677be04d407_bibliotecadb_tp.adb.oraclecloud.com))(security=(ssl_server_dn_match=no)))
      - DB_USERNAME=ADMIN
      - DB_PASSWORD=Biblioteca2026X
    restart: unless-stopped
    networks:
      - biblioteca-net
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8082/api/libros || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # ── FrontEnd Angular (Nginx) ──────────────────────────────────
  biblioteca-frontend:
    build:
      context: ./biblioteca-frontend
      dockerfile: Dockerfile
    container_name: biblioteca-frontend
    image: biblioteca-frontend:latest
    ports:
      - "4200:80"
    restart: unless-stopped
    networks:
      - biblioteca-net
    depends_on:
      biblioteca-backend:
        condition: service_started

# ── Red interna compartida entre servicios ────────────────────
networks:
  biblioteca-net:
    driver: bridge
