-- =========================================================
-- SCRIPT DE BASE DE DATOS ORACLE
-- Asignatura : Desarrollo Full Stack III (DSY2205)
-- Actividad  : Desarrollando nuestro microservicio
-- Alumno     : Cristobal Camps
-- =========================================================

-- ---------------------------------------------------------
-- PASO 1: Eliminar la tabla si ya existe
-- ---------------------------------------------------------
-- Esto sirve para comenzar desde cero durante el desarrollo.
-- CASCADE CONSTRAINTS elimina también restricciones asociadas.

DROP TABLE LIBROS CASCADE CONSTRAINTS;

-- ---------------------------------------------------------
-- PASO 2: Crear la tabla LIBROS
-- ---------------------------------------------------------
CREATE TABLE LIBROS (

    -- Campo id:
    -- Será la clave primaria de la tabla.
    -- GENERATED BY DEFAULT AS IDENTITY permite que Oracle
    -- genere automáticamente el valor del id.
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Campo titulo:
    -- Guarda el título del libro.
    -- NOT NULL obliga a que siempre tenga un valor.
    titulo VARCHAR2(200) NOT NULL,

    -- Campo autor:
    -- Guarda el nombre del autor del libro.
    -- También es obligatorio.
    autor VARCHAR2(200) NOT NULL,

    -- Campo anio_publicacion:
    -- Guarda el año de publicación del libro.
    -- Se deja como NUMBER porque almacenará un valor numérico.
    -- En Java este campo se llamará anioPublicacion.
    anio_publicacion NUMBER,

    -- Campo genero:
    -- Guarda el género literario del libro.
    -- También se define como obligatorio.
    genero VARCHAR2(100) NOT NULL
);

-- ---------------------------------------------------------
-- PASO 3: Insertar datos de prueba
-- ---------------------------------------------------------
-- Estos registros sirven para comprobar que la tabla funciona
-- y para verificar el endpoint GET en Postman o el navegador.

INSERT INTO LIBROS (titulo, autor, anio_publicacion, genero)
VALUES ('Clean Code', 'Robert C. Martin', 2008, 'Programacion');

INSERT INTO LIBROS (titulo, autor, anio_publicacion, genero)
VALUES ('El Principito', 'Antoine de Saint-Exupery', 1943, 'Ficcion');

INSERT INTO LIBROS (titulo, autor, anio_publicacion, genero)
VALUES ('Cien anos de soledad', 'Gabriel Garcia Marquez', 1967, 'Realismo magico');

INSERT INTO LIBROS (titulo, autor, anio_publicacion, genero)
VALUES ('1984', 'George Orwell', 1949, 'Ciencia ficcion');

INSERT INTO LIBROS (titulo, autor, anio_publicacion, genero)
VALUES ('Harry Potter y la piedra filosofal', 'J.K. Rowling', 1997, 'Fantasia');

-- ---------------------------------------------------------
-- PASO 4: Confirmar los cambios
-- ---------------------------------------------------------
COMMIT;

-- ---------------------------------------------------------
-- PASO 5: Verificar que la tabla y los datos existen
-- ---------------------------------------------------------
SELECT * FROM LIBROS;
