-- =========================================================
-- SCRIPT DE BASE DE DATOS ORACLE
-- Asignatura  : Desarrollo Full Stack III (DSY2205)
-- Actividad   : Programando nuestro BackEnd (Sumativa 1)
-- Alumno      : Cristobal Camps
-- =========================================================
-- INSTRUCCIONES DE USO:
-- Ejecutar cada seccion por separado en Oracle Database Actions SQL.
-- Copiar solo el bloque que necesitas y presionar Ejecutar (F5).
-- Si una tabla no existe aun, omitir el DROP correspondiente.
-- =========================================================


-- =========================================================
-- SECCION 1: TABLA LIBROS
-- =========================================================

DROP TABLE LIBROS CASCADE CONSTRAINTS;

CREATE TABLE LIBROS (
    id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo           VARCHAR2(200) NOT NULL,
    autor            VARCHAR2(200) NOT NULL,
    anio_publicacion NUMBER,
    genero           VARCHAR2(100) NOT NULL
);

INSERT INTO LIBROS (titulo, autor, anio_publicacion, genero) VALUES ('Clean Code', 'Robert C. Martin', 2008, 'Programacion');
INSERT INTO LIBROS (titulo, autor, anio_publicacion, genero) VALUES ('El Principito', 'Antoine de Saint-Exupery', 1943, 'Ficcion');
INSERT INTO LIBROS (titulo, autor, anio_publicacion, genero) VALUES ('Cien anos de soledad', 'Gabriel Garcia Marquez', 1967, 'Realismo magico');
INSERT INTO LIBROS (titulo, autor, anio_publicacion, genero) VALUES ('1984', 'George Orwell', 1949, 'Ciencia ficcion');
INSERT INTO LIBROS (titulo, autor, anio_publicacion, genero) VALUES ('Harry Potter y la piedra filosofal', 'J.K. Rowling', 1997, 'Fantasia');

COMMIT;
SELECT * FROM LIBROS;


-- =========================================================
-- SECCION 2: TABLA USUARIOS
-- =========================================================

DROP TABLE USUARIOS CASCADE CONSTRAINTS;

CREATE TABLE USUARIOS (
    id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre   VARCHAR2(100) NOT NULL,
    email    VARCHAR2(150) NOT NULL UNIQUE,
    password VARCHAR2(100) NOT NULL,
    rol      VARCHAR2(10)  NOT NULL CHECK (rol IN ('ADMIN', 'CLIENTE'))
);

INSERT INTO USUARIOS (nombre, email, password, rol) VALUES ('Carlos Administrador', 'admin@tienda.cl', 'Admin1234', 'ADMIN');
INSERT INTO USUARIOS (nombre, email, password, rol) VALUES ('Ana Gonzalez', 'ana.gonzalez@gmail.com', 'Cliente123', 'CLIENTE');
INSERT INTO USUARIOS (nombre, email, password, rol) VALUES ('Pedro Martinez', 'pedro.martinez@gmail.com', 'Cliente456', 'CLIENTE');
INSERT INTO USUARIOS (nombre, email, password, rol) VALUES ('Maria Lopez', 'maria.lopez@gmail.com', 'Cliente789', 'CLIENTE');

COMMIT;
SELECT * FROM USUARIOS;


-- =========================================================
-- SECCION 3: TABLA PRODUCTOS
-- =========================================================

DROP TABLE PRODUCTOS CASCADE CONSTRAINTS;

CREATE TABLE PRODUCTOS (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR2(200) NOT NULL,
    descripcion VARCHAR2(500) NOT NULL,
    precio      NUMBER(10, 2) NOT NULL,
    stock       NUMBER        NOT NULL,
    categoria   VARCHAR2(100) NOT NULL
);

INSERT INTO PRODUCTOS (nombre, descripcion, precio, stock, categoria) VALUES ('Laptop Dell Inspiron 15', 'Laptop Intel Core i5 12va gen, 8GB RAM, 512GB SSD, pantalla 15.6 Full HD.', 649990, 15, 'Laptops');
INSERT INTO PRODUCTOS (nombre, descripcion, precio, stock, categoria) VALUES ('Monitor LG 27 4K', 'Monitor UHD 4K 27 pulgadas panel IPS, 60Hz, HDMI y DisplayPort.', 389990, 8, 'Monitores');
INSERT INTO PRODUCTOS (nombre, descripcion, precio, stock, categoria) VALUES ('Teclado Mecanico Redragon K552', 'Teclado mecanico compacto switches Red, retroiluminacion RGB, estructura metal.', 49990, 30, 'Perifericos');
INSERT INTO PRODUCTOS (nombre, descripcion, precio, stock, categoria) VALUES ('Mouse Logitech MX Master 3', 'Mouse inalambrico ergonomico 4000 DPI, botones configurables, recarga USB-C.', 89990, 20, 'Perifericos');
INSERT INTO PRODUCTOS (nombre, descripcion, precio, stock, categoria) VALUES ('Audifonos Sony WH-1000XM5', 'Audifonos cancelacion de ruido, 30 horas bateria, audio alta resolucion.', 299990, 12, 'Audio');
INSERT INTO PRODUCTOS (nombre, descripcion, precio, stock, categoria) VALUES ('Webcam Logitech C920 HD Pro', 'Camara Full HD 1080p autofocus, microfono estereo, correccion de luz automatica.', 79990, 25, 'Accesorios');
INSERT INTO PRODUCTOS (nombre, descripcion, precio, stock, categoria) VALUES ('SSD Externo Samsung T7 1TB', 'Almacenamiento portatil 1TB, velocidad 1050 MB/s, conexion USB 3.2.', 119990, 18, 'Almacenamiento');

COMMIT;
SELECT * FROM PRODUCTOS;
