-- ============================================================
-- SCRIPT BD ORACLE CLOUD - TiendaOnline
-- DSY2205 - Desarrollo Full Stack III - Sumativa 3
-- Base de datos: BibliotecaDB (Oracle Autonomous)
-- ============================================================

-- ── Tabla USUARIOS ──────────────────────────────────────────
CREATE TABLE USUARIOS (
    ID       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOMBRE   VARCHAR2(100)  NOT NULL,
    EMAIL    VARCHAR2(150)  NOT NULL UNIQUE,
    PASSWORD VARCHAR2(100)  NOT NULL,
    ROL      VARCHAR2(10)   NOT NULL CHECK (ROL IN ('ADMIN','CLIENTE'))
);

-- Datos iniciales
INSERT INTO USUARIOS (NOMBRE, EMAIL, PASSWORD, ROL)
VALUES ('Admin TechStore', 'admin@techstore.cl', 'Admin@123', 'ADMIN');

INSERT INTO USUARIOS (NOMBRE, EMAIL, PASSWORD, ROL)
VALUES ('Juan Perez', 'juan@cliente.cl', 'Cliente@123', 'CLIENTE');

INSERT INTO USUARIOS (NOMBRE, EMAIL, PASSWORD, ROL)
VALUES ('Maria Gonzalez', 'maria@cliente.cl', 'Maria@456!', 'CLIENTE');

COMMIT;

-- ── Tabla PRODUCTOS ──────────────────────────────────────────
CREATE TABLE PRODUCTOS (
    ID          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOMBRE      VARCHAR2(200) NOT NULL,
    DESCRIPCION VARCHAR2(500) NOT NULL,
    PRECIO      NUMBER(12,2)  NOT NULL CHECK (PRECIO > 0),
    STOCK       NUMBER(10)    NOT NULL CHECK (STOCK >= 0),
    CATEGORIA   VARCHAR2(100) NOT NULL,
    DISPONIBLE  NUMBER(1)     DEFAULT 1 NOT NULL CHECK (DISPONIBLE IN (0,1))
);

-- Datos iniciales (7 productos)
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO, STOCK, CATEGORIA, DISPONIBLE)
VALUES ('Laptop ProBook 15',
        'Laptop de alto rendimiento con procesador Intel Core i7, 16GB RAM, SSD 512GB.',
        899990, 12, 'Computadores', 1);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO, STOCK, CATEGORIA, DISPONIBLE)
VALUES ('Smartphone Galaxy X20',
        'Smartphone 6.5" AMOLED, camara 108MP, bateria 5000mAh, 128GB almacenamiento.',
        499990, 25, 'Celulares', 1);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO, STOCK, CATEGORIA, DISPONIBLE)
VALUES ('Auriculares BT Pro',
        'Auriculares inalambricos Bluetooth 5.0, cancelacion de ruido activa, 30h bateria.',
        129990, 30, 'Audio', 1);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO, STOCK, CATEGORIA, DISPONIBLE)
VALUES ('Monitor 27" 4K UHD',
        'Monitor 4K UHD IPS 27 pulgadas, 144Hz, HDR400, ideal para diseno y gaming.',
        349990, 8, 'Monitores', 1);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO, STOCK, CATEGORIA, DISPONIBLE)
VALUES ('Teclado Mecanico RGB',
        'Teclado mecanico gaming con switches Blue, iluminacion RGB por tecla, USB-C.',
        79990, 40, 'Perifericos', 1);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO, STOCK, CATEGORIA, DISPONIBLE)
VALUES ('Mouse Inalambrico Ergo',
        'Mouse ergonomico inalambrico 2.4GHz, 4000 DPI, bateria recargable.',
        49990, 50, 'Perifericos', 1);

INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO, STOCK, CATEGORIA, DISPONIBLE)
VALUES ('Tablet ProPad 10"',
        'Tablet 10.5" FHD, 64GB almacenamiento, bateria 8000mAh, compatible con stylus.',
        299990, 15, 'Tablets', 0);

COMMIT;

-- ── Tabla PEDIDOS ────────────────────────────────────────────
CREATE TABLE PEDIDOS (
    ID          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    USUARIO_ID  NUMBER        NOT NULL REFERENCES USUARIOS(ID),
    TOTAL       NUMBER(12,2)  NOT NULL,
    ESTADO      VARCHAR2(20)  NOT NULL CHECK (ESTADO IN ('PENDIENTE','PROCESANDO','ENVIADO','ENTREGADO')),
    FECHA       DATE          DEFAULT SYSDATE NOT NULL
);

-- ── Tabla DETALLE_PEDIDOS ────────────────────────────────────
CREATE TABLE DETALLE_PEDIDOS (
    ID          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PEDIDO_ID   NUMBER        NOT NULL REFERENCES PEDIDOS(ID),
    PRODUCTO_ID NUMBER        NOT NULL REFERENCES PRODUCTOS(ID),
    CANTIDAD    NUMBER(5)     NOT NULL CHECK (CANTIDAD > 0),
    PRECIO_UNIT NUMBER(12,2)  NOT NULL
);

-- Datos iniciales de pedidos
INSERT INTO PEDIDOS (USUARIO_ID, TOTAL, ESTADO, FECHA)
VALUES (2, 899990, 'ENTREGADO', TO_DATE('2026-01-15','YYYY-MM-DD'));

INSERT INTO DETALLE_PEDIDOS (PEDIDO_ID, PRODUCTO_ID, CANTIDAD, PRECIO_UNIT)
VALUES (1, 1, 1, 899990);

INSERT INTO PEDIDOS (USUARIO_ID, TOTAL, ESTADO, FECHA)
VALUES (2, 339970, 'ENVIADO', TO_DATE('2026-03-20','YYYY-MM-DD'));

INSERT INTO DETALLE_PEDIDOS (PEDIDO_ID, PRODUCTO_ID, CANTIDAD, PRECIO_UNIT)
VALUES (2, 3, 2, 129990);
INSERT INTO DETALLE_PEDIDOS (PEDIDO_ID, PRODUCTO_ID, CANTIDAD, PRECIO_UNIT)
VALUES (2, 5, 1, 79990);

COMMIT;

-- ── Verificacion ─────────────────────────────────────────────
SELECT 'USUARIOS: '  || COUNT(*) FROM USUARIOS;
SELECT 'PRODUCTOS: ' || COUNT(*) FROM PRODUCTOS;
SELECT 'PEDIDOS: '   || COUNT(*) FROM PEDIDOS;
