
-- =========================================================
--  TABLA USUARIOS
-- =========================================================

DROP TABLE USUARIOS CASCADE CONSTRAINTS;

CREATE TABLE USUARIOS (
    id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre   VARCHAR2(100) NOT NULL,
    email    VARCHAR2(150) NOT NULL UNIQUE,
    password VARCHAR2(100) NOT NULL,
    rol      VARCHAR2(10)  NOT NULL CHECK (rol IN ('ADMIN', 'CLIENTE'))
);

INSERT INTO USUARIOS (nombre, email, password, rol) VALUES ('Carlos Administrador', 'admin@tienda.cl', 'Admin1234', 'ADMIN');
INSERT INTO USUARIOS (nombre, email, password, rol) VALUES ('Ana Gonzalez', 'ana.gonzalez@gmail.com', 'Cliente123', 'CLIENTE');
INSERT INTO USUARIOS (nombre, email, password, rol) VALUES ('Pedro Martinez', 'pedro.martinez@gmail.com', 'Cliente456', 'CLIENTE');
INSERT INTO USUARIOS (nombre, email, password, rol) VALUES ('Maria Lopez', 'maria.lopez@gmail.com', 'Cliente789', 'CLIENTE');

COMMIT;
SELECT * FROM USUARIOS;


-- =========================================================
--  TABLA PRODUCTOS
-- =========================================================

DROP TABLE PRODUCTOS CASCADE CONSTRAINTS;

CREATE TABLE PRODUCTOS (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR2(200) NOT NULL,
    descripcion VARCHAR2(500) NOT NULL,
    precio      NUMBER(10, 2) NOT NULL,
    stock       NUMBER        NOT NULL,
    categoria   VARCHAR2(100) NOT NULL
);

INSERT INTO PRODUCTOS (nombre, descripcion, precio, stock, categoria) VALUES ('Laptop Dell Inspiron 15', 'Laptop Intel Core i5 12va gen, 8GB RAM, 512GB SSD, pantalla 15.6 Full HD.', 649990, 15, 'Laptops');
INSERT INTO PRODUCTOS (nombre, descripcion, precio, stock, categoria) VALUES ('Monitor LG 27 4K', 'Monitor UHD 4K 27 pulgadas panel IPS, 60Hz, HDMI y DisplayPort.', 389990, 8, 'Monitores');
INSERT INTO PRODUCTOS (nombre, descripcion, precio, stock, categoria) VALUES ('Teclado Mecanico Redragon K552', 'Teclado mecanico compacto switches Red, retroiluminacion RGB, estructura metal.', 49990, 30, 'Perifericos');
INSERT INTO PRODUCTOS (nombre, descripcion, precio, stock, categoria) VALUES ('Mouse Logitech MX Master 3', 'Mouse inalambrico ergonomico 4000 DPI, botones configurables, recarga USB-C.', 89990, 20, 'Perifericos');
INSERT INTO PRODUCTOS (nombre, descripcion, precio, stock, categoria) VALUES ('Audifonos Sony WH-1000XM5', 'Audifonos cancelacion de ruido, 30 horas bateria, audio alta resolucion.', 299990, 12, 'Audio');
INSERT INTO PRODUCTOS (nombre, descripcion, precio, stock, categoria) VALUES ('Webcam Logitech C920 HD Pro', 'Camara Full HD 1080p autofocus, microfono estereo, correccion de luz automatica.', 79990, 25, 'Accesorios');
INSERT INTO PRODUCTOS (nombre, descripcion, precio, stock, categoria) VALUES ('SSD Externo Samsung T7 1TB', 'Almacenamiento portatil 1TB, velocidad 1050 MB/s, conexion USB 3.2.', 119990, 18, 'Almacenamiento');

COMMIT;
SELECT * FROM PRODUCTOS;
