# Este archivo fue creado por error durante la Sumativa 2.
# biblioteca-s4 no forma parte de la entrega de esta evaluación.
# El caso de la Sumativa 2 es TechStore (tienda en línea),
# cuyos microservicios son: tienda-frontend y ms-pedidos.
