# =============================================================
# SonarQube Configuration - TiendaOnline Frontend
# DSY2205 - Desarrollo Full Stack III - Sumativa 3
# =============================================================

# --- Identificación del proyecto ---
sonar.projectKey=tienda-online-frontend
sonar.projectName=TiendaOnline - Frontend Angular
sonar.projectVersion=1.0

# --- Fuentes ---
sonar.sources=src
sonar.tests=src
sonar.inclusions=**/*.ts,**/*.html
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.ts,**/environments/**,**/main.ts,**/polyfills.ts

# --- Tests ---
sonar.test.inclusions=**/*.spec.ts

# --- Cobertura ---
# Generado por Karma con karma-coverage en formato lcov
sonar.javascript.lcov.reportPaths=coverage/tienda-frontend/lcov.info

# --- TypeScript ---
sonar.typescript.tsconfigPath=tsconfig.json

# --- Servidor SonarQube (local, sin Docker) ---
sonar.host.url=http://localhost:9000
sonar.token=sqa_50fbba940893aa1d52137f925ee7b3cc70f458fd

# --- Encoding ---
sonar.sourceEncoding=UTF-8
